type: object
patternProperties:
  '^pkg$':
    type: object
    patternProperties:
      '':
        type: object
        properties:
          tag:
            type: string
          msg:
            type: string
          web:
            type: string
            format: uri
          doc:
            type: string
            format: uri
          use:
            type: array
            items:
              type: string
              pattern: '^(?!pkg\.)'
            minContains: 1
          exp:
            type: string
            enum:
              - stable
              - unstable
            default: unstable
        required:
          - tag
          - msg
          - web
          - use
        additionalProperties: false
  '^(?!pkg$)':
    type: object
    patternProperties:
      '':
        type: object
        properties:
          sum:
            type: string
          url:
            type: string
            format: uri
        required:
          - url
        additionalProperties: false
