on:
  push:
    branches:
    - 'master'
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  actions: write
  pages: write
env:
  bin: target/release/bot
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: |
        cargo build --release
        gh release create bot || true
        gh release upload bot $bin --clobber
    if: github.event_name == 'push'
  Prepare:
    needs: Compile
    runs-on: ubuntu-latest
    steps:
    - run: |
        gh release download bot -R $GITHUB_REPOSITORY
        sudo chmod a+x bot
        ./bot > market.json
        rm bot
    - uses: actions/configure-pages@v2
    - uses: actions/jekyll-build-pages@v1
    - uses: actions/upload-pages-artifact@v1
    if: ${{!failure()}}
  Publish:
    needs: Prepare
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/deploy-pages@v1
    if: ${{!failure()}}
  Sustain:
    runs-on: ubuntu-latest
    steps:
    - run: gh workflow enable build.yaml
      env:
        GH_REPO: ${{github.repository}}
